version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
